name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        db_engine: ${{ secrets.db_engine}}
        db_name: ${{ secrets.db_name}}
        db_host: ${{ secrets.db_host}}
        db_user: ${{ secrets.db_user}}
        db_password: ${{ secrets.db_password}}
        db_port: ${{ secrets.db_port}}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS}}
        CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS}}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
